#!/bin/bash
rm all_activities
for i in `ls *.json`; 
	do echo $i >> all_activities;
	jq '.[] | .description | select(. != null)' $i >> all_activities
	#cat $i | jq '.metadata[] .class' >> all_activities
	done;

